/* Node built-ins only; exercises category boundaries and copyable evidence. */
'use strict';
const assert = require('node:assert/strict');
require('../assets/review-tools.js');
const tools = globalThis.ReviewTools;
assert.equal(tools.category('app/views/rentals/show.html.erb'), 'Design / UI');
assert.equal(tools.category('app/assets/stylesheets/rentals.scss'), 'Design / UI');
assert.equal(tools.category('app/javascript/controllers/rental_controller.js'), 'Frontend');
assert.equal(tools.category('app/javascript/controllers/rental_controller.js', {'app/javascript/controllers/rental_controller.js':'Design / UI'}), 'Frontend');
assert.equal(tools.category('app/helpers/rentals_helper.rb'), 'Frontend');
assert.equal(tools.category('app/controllers/rentals_controller.rb'), 'Backend');
assert.equal(tools.category('app/controllers/rentals_controller.rb', {'app/controllers/rentals_controller.rb':'Frontend'}), 'Frontend');
assert.equal(tools.category('test/controllers/rentals_controller_test.rb'), 'Tests');
assert.equal(tools.category('app/policies/rental_policy.rb'), 'Security');
assert.equal(tools.category('docs/setup.md'), 'Documentation');
assert.equal(tools.category('AGENTS.md'), 'AI');
assert.equal(tools.category('db/schema.rb'), 'Backend');
assert.equal(tools.category('db/structure.sql'), 'Backend');
assert.equal(tools.category('db/migrate/20260907120000_add_permissions.rb'), 'Backend');
assert.equal(tools.category('config/routes.rb'), 'Backend');
assert.equal(tools.category('.github/workflows/test.yml'), 'Platform');
assert.equal(tools.category('config/environments/development.rb'), 'Platform');
assert.equal(tools.category('vite.config.js'), 'Platform');
assert.equal(tools.category('data/catalog.yml'), 'Other');
console.log('PASS responsibility grouping keeps behavior out of Design / UI');
const snapshot = {head:'abc123',base:'old123',created:'2026-09-07',mode:'uncommitted',fingerprint:'snapshot1',files:[{path:'app/example.rb',hunks:[{id:'h1',rows:{unified:[{kind:'context',old:9,new:10,text:'before()'},{kind:'del',old:10,text:'unsafe()'},{kind:'add',new:11,text:'safe()'},{kind:'add',new:12,text:'~~~~'},{kind:'context',old:11,new:13,text:'after()'}]}}]}]};
const comment = {hunk:'h1',side:'new',start:11,end:12,label:'suggestion',decoration:'non-blocking',subject:'Check the fallback',discussion:'Use the existing behavior.'};
const copied = tools.commentText(snapshot, comment);
assert.match(copied, /File: app\/example.rb/);
assert.match(copied, /After lines 11–12/);
assert.match(copied, /working tree captured at 2026-09-07/);
assert.match(copied, /11 \| safe\(\)/);
assert.match(copied, /~~~~~\n11/);
assert.ok(!copied.includes('unsafe()'));
assert.ok(!copied.includes('after()'));
assert.match(copied, /suggestion \(non-blocking\): Check the fallback/);
assert.match(tools.commentText(snapshot, {...comment,side:'old',start:10,end:10}), /10 \| unsafe\(\)/);
assert.equal(tools.anchor(snapshot,{...comment,end:15}), null);
assert.throws(()=>tools.commentText(snapshot,{...comment,hunk:'missing'}));
console.log('PASS copy includes exact source side, lines, snippet and comment');
const combined = tools.reviewText(snapshot,[comment],[{title:'Extra checks',paths:['app/example.rb'],text:'A step note'}]);
assert.match(combined,/Snapshot: snapshot1/);
assert.match(combined,/Step: Extra checks/);
assert.match(combined,/A step note/);
const resolved = tools.reviewText(snapshot,[{...comment,resolved:true}]);
assert.match(resolved,/Conversation: resolved locally \(not verification that the code was fixed\)/);
assert.match(resolved,/11 \| safe\(\)/);
assert.match(resolved,/Check the fallback/);
console.log('PASS combined review retains comments and personal step notes');
const issue = {id:'c1', label:'issue', hunk:'h1'};
const finding = {id:'F1', hunk:'h1', severity:'P2'};
const review = {comments:[issue],findings:[finding]};
assert.deepEqual(tools.overviewFeedback(review), {comments:[{...issue,severity:'P2'}],findings:[]});
assert.equal(issue.severity, undefined);
assert.equal(tools.overviewFeedback({comments:[{...issue,label:'note'}],findings:[finding]}).findings.length,1);
assert.equal(tools.overviewFeedback({comments:[issue],findings:[finding,{...finding,id:'F2'}]}).findings.length,2);
assert.equal(tools.overviewFeedback({comments:[issue,{...issue,id:'c2'}],findings:[finding]}).findings.length,1);
assert.equal(tools.overviewFeedback({comments:[issue,{...issue,id:'c2'}],findings:[{...finding,comment_id:'c1'}]}).findings.length,0);
assert.equal(tools.overviewFeedback({comments:[issue],findings:[{...finding,comment_id:'missing'}]}).findings.length,1);
assert.deepEqual(tools.overviewFeedback({}),{comments:[],findings:[]});
console.log('PASS overview deduplicates only matching issues and retains unmatched findings');
const endpoints = {mode:'pr',base:'abcdef123',head:'123456789'};
const comparison = {base:endpoints.base,head:endpoints.head,base_label:'main',head_label:'feat/inbox',pr_number:123};
assert.match(tools.comparisonText(endpoints,{comparison}), /PR #123 · feat\/inbox compared with main/);
assert.match(tools.comparisonText({...endpoints,head:'newhead123'},{comparison}), /newhead1 compared with abcdef12/);
assert.match(tools.comparisonText({...endpoints,mode:'uncommitted'},{comparison}), /^Uncommitted changes .*HEAD$/);
assert.match(tools.comparisonText({...endpoints,mode:'commit'}), /^Commit review · 12345678 compared with abcdef12/);
assert.match(tools.comparisonText({...endpoints,mode:'series',working_tree:true},{comparison,history:{origin_mode:'uncommitted'}}), /^Cumulative review · committed and uncommitted changes compared with main$/);
assert.match(tools.comparisonText({...endpoints,mode:'series',working_tree:false},{comparison,history:{origin_mode:'pr'}}), /^PR #123/);
assert.match(tools.comparisonText({...endpoints,mode:'series',working_tree:false}), /^Cumulative review/);
const qa = {flows:[{assets:[{comment_id:'c1'},{comment_id:'c1'}]},{assets:[]},{assets:[{comment_id:'c1'}]}]};
assert.deepEqual(tools.evidenceFlows(qa,{id:'c1'}),[0,2]);
assert.deepEqual(tools.evidenceFlows(qa,{id:'c1',personal:true}),[]);
assert.deepEqual(tools.evidenceFlows(undefined,{id:'c1'}),[]);
console.log('PASS scope labels distinguish review modes and evidence links target unique flows');
const evidenceComment = {...comment,id:'c1',discussion:''};
const evidenceQA = {flows:[{comment_id:'c1',steps:['Open the list.','Reopen the conversation.'],expected:'Row returns.',observed:'Row is missing.',assets:[]}]};
const post = tools.postingText(snapshot,evidenceComment,evidenceQA);
assert.match(post,/File: app\/example.rb \(after lines 11–12\)/);
assert.match(post,/1\. Open the list\.\n2\. Reopen the conversation\./);
assert.match(post,/Expected: Row returns\.\nActual: Row is missing\./);
assert.ok(!post.includes('safe()') && !post.includes('Source:') && !post.includes('resolved locally'));
assert.match(tools.commentText(snapshot,evidenceComment,evidenceQA),/11 \| safe\(\)/);
assert.match(tools.commentText(snapshot,evidenceComment,evidenceQA),/2\. Reopen the conversation\./);
const general = {id:'mine-general',general:true,personal:true,label:'question',decoration:'non-blocking',subject:'Check the empty list',discussion:'Can we clarify the empty state?',resolved:true};
assert.match(tools.commentText(snapshot,general),/General comment · abc123/);
assert.match(tools.commentText(snapshot,general),/resolved locally/);
assert.ok(!tools.postingText(snapshot,general).includes('File:'));
assert.ok(!tools.postingText(snapshot,general).includes('resolved locally'));
const allUser = tools.reviewText(snapshot,[general,{...comment,personal:true}],[{title:'Step',paths:['app/example.rb'],text:'Keep this note'}]);
assert.match(allUser,/Check the empty list/);assert.match(allUser,/11 \| safe\(\)/);assert.match(allUser,/Keep this note/);
assert.deepEqual(tools.evidenceFlows(evidenceQA,evidenceComment),[0]);
assert.equal(tools.flowOwner({comment_id:'c1',assets:[{comment_id:'c2'}]}),'c1');
assert.equal(tools.flowOwner({assets:[{comment_id:'c1'},{comment_id:'c2'}]}),'c1');
console.log('PASS posting and LLM copies retain reproduction; general and anchored user comments combine safely');
